name: Build PNPM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install with pnpm
      working-directory: electron-app
      run: |
        pnpm install --no-frozen-lockfile
        pnpm list

    - name: Build with pnpm
      working-directory: electron-app
      run: pnpm run build-win

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: StreamVoice-PNPM
        path: electron-app/dist/*.exe