name: Test Ubuntu

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: electron-app
      run: |
        npm install

    - name: Try Linux build
      working-directory: electron-app
      run: |
        npm run dist -- --linux

    - name: Upload
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ubuntu-build
        path: electron-app/dist/